// ─────────────────────────────────────────────────────────────────────────────
// persons.ts — add or remove names here, one per line.
// This is the only file you need to touch to change the person pool.
//
// Rules:
//   • Each name must be a string in double quotes, ending with a comma.
//   • The list needs at least as many names as the max number of players (12).
//   • Names should be well-known enough that most players recognise them.
// ─────────────────────────────────────────────────────────────────────────────

export const FAMOUS_PERSONS: string[] = [
"Adolf Hitler",
  "Sheik Mujibur Rahman",
  "Tarek Zia",
  "Mark Zuckerberg",
  "Isaac Newton",
  "Albert Einstein",
  "Nikola Tesla",
  "Cristiano Ronaldo",
  "MrBeast",
  "PewDiePie",
  "Osama bin Laden",
  "Benjamin Netanyahu",
  "Donald Trump",
  "Vladimir Putin",
  "Pope Francis",
  "Elon Musk",
  "Barack Obama",
  "Queen Elizabeth II",

  // Bangladeshi Context (Legends, Culture & Sports)
  "Shakib Al Hasan",
  "Hero Alom",
  "Dr. Muhammad Yunus",
  "Rabindranath Tagore",
  "Kazi Nazrul Islam",
  "Humayun Ahmed",
  "James",
  "Ayub Bachchu",
  "Chanchal Chowdhury",
  "Mashrafe Mortaza",
  "Tahsan Khan",
  "Runa Laila",
  "Zainul Abedin",

  "Prophet Muhammad",
  "Prophet Ibrahim",
  "Prophet Musa",
  "Prophet Isa",
  "Prophet Nuh",
  "Prophet Yusuf",
  "Prophet Dawud",
  "Prophet Sulayman",
  "Abu Bakr",
  "Omar bin Khattab",
  "Ali bin Abi Talib",
  "Lalon Shah",
  "Jesus of Nazareth",
  "Moses",
  "Abraham",
  "Saint Peter",
  "Paul the Apostle",
  "John the Baptist",
  "Martin Luther",
  "John Calvin",
  "King David",
  "Mary, Mother of Jesus",
  "Lord Krishna",
  "Lord Rama",
  "Swami Vivekananda",
  "Ramakrishna Paramahamsa",
  "Chaitanya Mahaprabhu",
  "Gautama Buddha",
  "Guru Nanak",
  "Confucius",
  "Laozi",
  "Mahavira",
  "Zoroaster",
  "Dalai Lama",

  // Asian Context (Bollywood, K-Pop, Gaming & Icons)
  "Shah Rukh Khan",
  "Virat Kohli",
  "Sachin Tendulkar",
  "Amitabh Bachchan",
  "Salman Khan",
  "Aamir Khan",
  "Jackie Chan",
  "Bruce Lee",
  "Jungkook",
  "Lisa",
  "Kim Jong Un",
  "Mahatma Gandhi",
  "Narendra Modi",
  "Son Heung-min",
  "Jack Ma",
  "Hayao Miyazaki",
  "Akira Toriyama",

  "Sheikh Hasina",
  "Khaleda Zia",
  "Hussain Muhammad Ershad",
  "Ziaur Rahman",
  "Tajuddin Ahmad",
  "A. K. Fazlul Huq",
  "Huseyn Shaheed Suhrawardy",
  "Abdul Hamid Khan Bhashani",
  "Obaidul Quader",
  "Mirza Fakhrul Islam Alamgir",
  "Xi Jinping",
  "Kim Jong Il",
  "Mao Zedong",
  "Ho Chi Minh",
  "Lee Kuan Yew",
  "Jawaharlal Nehru",
  "Imran Khan",
  "Zulfikar Ali Bhutto",
  "Benazir Bhutto",
  "Mahathir Mohamad",
  "Ferdinand Marcos",
  "Joe Biden",
  "Bill Clinton",
  "George W. Bush",
  "John F. Kennedy",
  "Richard Nixon",
  "Franklin D. Roosevelt",
  "Winston Churchill",
  "Margaret Thatcher",
  "Angela Merkel",
  "Emmanuel Macron",
  "Boris Johnson",
  "Julius Caesar",
  "Alexander the Great",
  "Napoleon Bonaparte",
  "Joseph Stalin",
  "Fidel Castro",
  "Che Guevara",
  "Muammar Gaddafi",
  "Saddam Hussein",
  "Nelson Mandela",
  "Winston Churchill",

  "Genghis Khan",
  "Kublai Khan",
  "Attila the Hun",
  "Timur",
  "Sun Tzu",
  "Cao Cao",
  "Oda Nobunaga",
  "Toyotomi Hideyoshi",
  "Tokugawa Ieyasu",
  "Hannibal Barca",
  "Spartacus",
  "Richard the Lionheart",
  "Saladin",
  "Joan of Arc",
  "Hernán Cortés",
  "Francisco Pizarro",
  "Duke of Wellington",
  "Erwin Rommel",
  "Douglas MacArthur",
  "Emperor Ashoka",
  "Chandragupta Maurya",
  "Samudragupta",
  "Chhatrapati Shivaji",
  "Prithviraj Chauhan",
  "Tipu Sultan",
  "Sher Shah Suri",
  "Alauddin Khalji",
  "Khalid Ibn Al Walid",
  "Isa Khan",

  // More Global Heavyweights (High-key essential)
  "Lionel Messi",
  "Taylor Swift",
  "Billie Eilish",
  "Cleopatra",
  "Malala Yousafzai",
  "Ada Lovelace",
  "Beyoncé",
  "Drake",
  "Indira Gandhi",
  "Mother Teresa",
  "Scarlett Johansson",
  "Zendaya",
  "Emma Watson",
  "Marie Curie ",
  "Queen Elizabeth I",
  "Queen Elizabeth III",
  "LeBron James",
  "Michael Jordan",
  "Steve Jobs",
  "Bill Gates",
  "Leonardo DiCaprio",
  "Johnny Depp",
  "Tom Cruise",
  "Angelina Jolie",
  "Keanu Reeves",
  "Rihanna"
];
